"""add_waiter_lifetime_stats

Revision ID: 885e2489fc5a
Revises: 20260115_1200
Create Date: 2026-01-17 19:36:30.388292+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885e2489fc5a'
down_revision: Union[str, None] = '20260115_1200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiters', sa.Column('total_tables_served', sa.Integer(), server_default='0', nullable=False))
    op.add_column('waiters', sa.Column('total_sales', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiters', 'total_sales')
    op.drop_column('waiters', 'total_tables_served')
    # ### end Alembic commands ###
