"""initial schema with review system

Revision ID: 50c26d1f63a9
Revises: 
Create Date: 2026-01-17 19:59:37.490476+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50c26d1f63a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('yelp_url', sa.String(length=500), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_sources',
    sa.Column('camera_id', sa.String(length=128), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=True),
    sa.Column('video_source', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('pos_item_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'pos_item_id', name='uq_restaurant_pos_item')
    )
    op.create_table('restaurant_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('total_parties', sa.Integer(), nullable=False),
    sa.Column('total_covers', sa.Integer(), nullable=False),
    sa.Column('peak_occupancy', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tips', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_check_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_turn_time_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_wait_time_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('waiter_count', sa.Integer(), nullable=True),
    sa.Column('covers_per_waiter', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'period_type', 'period_start', name='uq_restaurant_metrics_lookup')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('review_identifier', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('review_date', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('category_opinions', sa.JSON(), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_identifier')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tier_updated_at', sa.DateTime(), nullable=True),
    sa.Column('total_shifts', sa.Integer(), nullable=False),
    sa.Column('total_covers', sa.Integer(), nullable=False),
    sa.Column('total_tips', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('party_name', sa.String(length=100), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('table_preference', sa.String(length=20), nullable=True),
    sa.Column('location_preference', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.Column('quoted_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seated_at', sa.DateTime(), nullable=True),
    sa.Column('walked_away_at', sa.DateTime(), nullable=True),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_crop_state',
    sa.Column('camera_id', sa.String(length=128), nullable=False),
    sa.Column('crop_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_capture_ts', sa.DateTime(), nullable=True),
    sa.Column('last_frame_index', sa.Integer(), nullable=True),
    sa.Column('last_dispatched_frame_index', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_sources.camera_id'], ),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('crop_dispatch_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(length=128), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera_sources.camera_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'table_id', 'frame_index', name='uq_crop_dispatch_camera_table_frame')
    )
    op.create_table('menu_item_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('times_ordered', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hourly_distribution', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id', 'period_type', 'period_start', name='uq_menu_item_metrics_lookup')
    )
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('waiter_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tables_served', sa.Integer(), nullable=False),
    sa.Column('total_covers', sa.Integer(), nullable=False),
    sa.Column('total_tips', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['waiter_id'], ['waiters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('table_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('table_type', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('state_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('state_updated_at', sa.DateTime(), nullable=True),
    sa.Column('current_visit_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'table_number', name='uq_restaurant_table_number')
    )
    op.create_table('table_state_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('previous_state', sa.String(length=20), nullable=True),
    sa.Column('new_state', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('waiter_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('waitlist_id', sa.UUID(), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('actual_covers', sa.Integer(), nullable=True),
    sa.Column('seated_at', sa.DateTime(), nullable=False),
    sa.Column('first_served_at', sa.DateTime(), nullable=True),
    sa.Column('payment_at', sa.DateTime(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tip', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tip_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pos_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('original_waiter_id', sa.UUID(), nullable=True),
    sa.Column('transferred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_waiter_id'], ['waiters.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['waiter_id'], ['waiters.id'], ),
    sa.ForeignKeyConstraint(['waitlist_id'], ['waitlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiter_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('waiter_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('tables_served', sa.Integer(), nullable=False),
    sa.Column('total_covers', sa.Integer(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tips', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_tip_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_check_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_turn_time_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('min_turn_time_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_turn_time_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['waiter_id'], ['waiters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('waiter_id', 'period_type', 'period_start', 'shift_id', name='uq_waiter_metrics_lookup')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('modifiers', sa.JSON(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('waiter_metrics')
    op.drop_table('visits')
    op.drop_table('table_state_log')
    op.drop_table('tables')
    op.drop_table('shifts')
    op.drop_table('menu_item_metrics')
    op.drop_table('crop_dispatch_log')
    op.drop_table('camera_crop_state')
    op.drop_table('waitlist')
    op.drop_table('waiters')
    op.drop_table('sections')
    op.drop_table('reviews')
    op.drop_table('restaurant_metrics')
    op.drop_table('menu_items')
    op.drop_table('camera_sources')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
